#!/usr/bin/env bash
# 1-click setup for the For You sidecar.
#
# Detects OS + GPU vendor + group IDs and writes:
#   • .env                         — compose profiles + ollama image tag
#   • docker-compose.override.yml  — GPU passthrough for ollama service
#
# Re-runnable; safe to invoke after a kernel upgrade or GPU swap.
set -euo pipefail

cd "$(dirname "$0")"

# ── tiny logger ─────────────────────────────────────────────────────────────
c_ok()    { printf '\033[32m✓\033[0m %s\n' "$1"; }
c_info()  { printf '\033[36m→\033[0m %s\n' "$1"; }
c_warn()  { printf '\033[33m!\033[0m %s\n' "$1"; }
c_err()   { printf '\033[31m✗\033[0m %s\n' "$1" >&2; }

# ── detect OS ───────────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux*) ;;
  Darwin*)
    c_warn "macOS detected — Docker Desktop on Mac does not expose host GPUs."
    c_warn "  Apple Silicon users get the best speed by running Ollama natively"
    c_warn "  outside Docker and pointing FORYOU_OLLAMA_URL at it."
    c_warn "  Continuing with CPU-only setup inside Docker."
    ;;
  *)
    c_warn "Unrecognised OS ($OS); assuming CPU-only."
    ;;
esac

# ── detect GPU ──────────────────────────────────────────────────────────────
GPU_KIND=none           # none | nvidia | amd
GPU_LABEL=""
NVIDIA_TOOLKIT_OK=0
AMD_KFD_OK=0

if [[ "$OS" == "Linux" ]] && command -v lspci >/dev/null 2>&1; then
  if lspci -nn | grep -qi nvidia; then
    GPU_KIND=nvidia
    GPU_LABEL="$(lspci -nn | grep -i 'vga\|3d\|display' | grep -i nvidia | head -1 | sed 's/.*: //')"
  elif lspci -nn | grep -iE 'amd/ati|advanced micro' | grep -iE 'vga|3d|display' >/dev/null 2>&1; then
    GPU_KIND=amd
    GPU_LABEL="$(lspci -nn | grep -iE 'vga|3d|display' | grep -iE 'amd/ati|advanced micro' | head -1 | sed 's/.*: //')"
  fi
fi

case "$GPU_KIND" in
  nvidia)
    c_info "GPU: $GPU_LABEL"
    # Check for NVIDIA Container Toolkit (or nvidia runtime in docker info).
    if docker info 2>/dev/null | grep -qi 'Runtimes:.*nvidia' \
       || command -v nvidia-container-toolkit >/dev/null 2>&1 \
       || command -v nvidia-container-cli >/dev/null 2>&1; then
      NVIDIA_TOOLKIT_OK=1
      c_ok   "NVIDIA Container Toolkit detected."
    else
      c_warn "NVIDIA Container Toolkit missing — Docker can't reach the GPU."
      c_warn "  Install it (e.g. on Manjaro/Arch: dpr install nvidia-container-toolkit"
      c_warn "  then restart docker). Falling back to CPU-only for now."
      GPU_KIND=none
    fi
    ;;
  amd)
    c_info "GPU: $GPU_LABEL"
    if [[ -e /dev/kfd && -e /dev/dri ]]; then
      AMD_KFD_OK=1
      c_ok "amdgpu kernel driver + /dev/kfd + /dev/dri present."
    else
      c_warn "amdgpu kernel driver not exposing /dev/kfd — using CPU."
      GPU_KIND=none
    fi
    ;;
  none)
    c_info "No discrete GPU detected — using CPU. (Ollama still works, just slower.)"
    ;;
esac

# ── decide image + groups ───────────────────────────────────────────────────
OLLAMA_IMAGE="ollama/ollama:latest"
RENDER_GID=""
VIDEO_GID=""

if [[ "$GPU_KIND" == "amd" ]]; then
  OLLAMA_IMAGE="ollama/ollama:rocm"
  RENDER_GID="$(getent group render 2>/dev/null | cut -d: -f3 || true)"
  VIDEO_GID="$(getent group video  2>/dev/null | cut -d: -f3 || true)"
  [[ -z "$RENDER_GID" ]] && c_warn "group 'render' not found; container may need --privileged."
  [[ -z "$VIDEO_GID"  ]] && c_warn "group 'video' not found; container may need --privileged."
fi

# ── write .env (preserve user overrides) ────────────────────────────────────
ENV_FILE=".env"
touch "$ENV_FILE"

set_env_var() {
  local key="$1" val="$2"
  if grep -qE "^${key}=" "$ENV_FILE"; then
    # POSIX-portable sed: write to temp + mv (avoids -i differences).
    awk -v k="$key" -v v="$val" 'BEGIN{FS=OFS="="} $1==k {$0=k"="v} {print}' \
      "$ENV_FILE" > "$ENV_FILE.tmp" && mv "$ENV_FILE.tmp" "$ENV_FILE"
  else
    printf '%s=%s\n' "$key" "$val" >> "$ENV_FILE"
  fi
}

set_env_var COMPOSE_PROFILES "cookies,foryou"
set_env_var OLLAMA_IMAGE     "$OLLAMA_IMAGE"
c_ok ".env updated (COMPOSE_PROFILES=cookies,foryou OLLAMA_IMAGE=$OLLAMA_IMAGE)"

# ── write docker-compose.override.yml ───────────────────────────────────────
OVERRIDE_FILE="docker-compose.override.yml"
MARK="# Generated by setup-foryou.sh — re-run that script to update."

case "$GPU_KIND" in
  nvidia)
    cat > "$OVERRIDE_FILE" <<EOF
$MARK
services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
EOF
    c_ok "$OVERRIDE_FILE written for NVIDIA GPU passthrough."
    ;;
  amd)
    {
      printf '%s\nservices:\n  ollama:\n    devices:\n      - /dev/kfd\n      - /dev/dri\n' "$MARK"
      if [[ -n "$VIDEO_GID$RENDER_GID" ]]; then
        printf '    group_add:\n'
        [[ -n "$VIDEO_GID"  ]] && printf '      - "%s"   # video\n'  "$VIDEO_GID"
        [[ -n "$RENDER_GID" ]] && printf '      - "%s"   # render\n' "$RENDER_GID"
      fi
    } > "$OVERRIDE_FILE"
    c_ok "$OVERRIDE_FILE written for AMD ROCm passthrough (video=$VIDEO_GID render=$RENDER_GID)."
    ;;
  *)
    if [[ -f "$OVERRIDE_FILE" ]] && head -1 "$OVERRIDE_FILE" | grep -q 'setup-foryou.sh'; then
      rm -f "$OVERRIDE_FILE"
      c_ok "Removed stale $OVERRIDE_FILE (no GPU)."
    fi
    ;;
esac

# ── next steps ──────────────────────────────────────────────────────────────
cat <<'EOF'

────────────────────────────────────────────────────────────────────────
Setup done. Bring up the stack:

  docker compose build && docker compose down && docker compose up -d

Then watch the first-boot model pull (~3.5 GB, only the first time):

  docker compose logs -f foryou ollama

Re-run this script after any GPU/driver change, after switching machines,
or if Docker complains about missing devices.
────────────────────────────────────────────────────────────────────────
EOF
